### ISSUE TITLE
Fix Watchdog's error function handling.

### ISSUE THREAD

**Issue by boguslaw-wojcik** [msales/streams#28]
Despite having an error function set for a task (http://prntscr.com/m2kjd2) on top level on commit error the watchdog crashes on nil pointer (http://prntscr.com/m2jno1).

**Comment by nrwiersma** [comment]
We are passing the wrong error handling function to the TimedSupervisor. Will be fixed ASAP.

**Comment by nrwiersma** [comment]
Fixed in #30
