### ISSUE TITLE
Committer method should receive context as an argument.

### ISSUE THREAD

**Issue by boguslaw-wojcik** [msales/streams#29]
Issue: A commit method might want to log / stat something and needs context for that job.

Workaround: Store entire message in an internal comitter batch and use context from last message.

Solution: Pass current context to comitter.

Why: It's cleaner and you can for instance batch only processed events and not entire messages, increasing performance this way (more work is shifted to stream processing instead of atomic commit).

**Comment by nrwiersma** [comment]
We dont have the context. Context is added to messages by the `Source`. The Committer object would need to get the Context externally.

**Comment by nrwiersma** [comment]
This has been addressed in #33 and will be released in `v3`.
