### ISSUE TITLE
Pipe Mock panics for slices and maps

### ISSUE THREAD

**Issue by boguslaw-wojcik** [msales/streams#44]
Eg.: Expectation

ExpectForward(nil, []byte{0,1,2,3})

will panic if mock is subject to

Forward(streams.Message{
Value: []byte{0,1,2,3}
})

Solution: eg. use ObjectsAreEqual from github.com/stretchr/testify/assert instead of hard comparison in streams/mocks/pipe.go in 61:62, 83:84, 107:108.

Also a side suggestion: When introducing mocks it is convenient to make expectation methods chain-able, so you can use mocks inline within test cases, like:

(mocks.NewPipeMock()).ExpectMark(...).ExpectMark(...).Commit()

**Comment by nrwiersma** [comment]
Fixed in #48
